### ISSUE TITLE
[EPIC] Implement Custom War Generation

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#12]
- [x] Implement generation of  packager-config.yml

- [x] Implement Editor to show the generated packager-config.yml

- [x] Implement generation of WAR using CWP libraries

- [x] Implement ability to download generated WAR package.

**Comment by sladyn98** [comment]
This has been completed with the ability to download war packages in #68
