### ISSUE TITLE
[EPIC] Render home page

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#5]
- [x] Render individual plugin cards [#6]

- [x] Add feature to search plugins [#8]

- [ ] Add feature to filter plugins [#9]

- [x] Add feature to add plugins to the custom configuration [#10]

**Comment by kwhetstone** [comment]
This sounds good.  Let's get a UI mockup picture in this epic to at least see what we're aiming for.  That way, you can share it out on the channel for tweaks before you go through implementing something that eventually your end users might not prefer.
